name: Cypress Tests on Push

on:
  push:
    branches:
      - main  # or any other branch you want to trigger on

jobs:
  cypress-tests:
    runs-on: ubuntu-latest  # You can use other OSes as needed

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set your required Node version

      - name: Delete cache before running tests
        run: |
          rm -rf node_modules
          rm -rf ~/.cache
          echo "Cache cleared before running tests"

      - name: Install dependencies
        run: |
          npm install

      - name: Run Cypress tests
        run: |
          npx cypress run --headless  # Add other Cypress options as required

      - name: Delete cache after running tests
        run: |
          rm -rf node_modules
          rm -rf ~/.cache
          echo "Cache cleared after tests"

      - name: Upload Cypress results (optional)
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/results
