name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache node_modules to speed up installation
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start  # If you need to start your app before running tests
          wait-on: 'http://localhost:3000'  # Wait for the app to be ready
