# jobs:
#   cypress-run:
#       runs-on: ubuntu-24.04
#         steps:
#          - name: Checkout
#            uses: actions/checkout@v4
        
#          - name: Cache node_modules
#            uses: actions/cache@v2
#         with:
#           path: node_modules
#           key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.os }}-node-modules-

#             - name: Install dependencies
#                 run: npm ci

#             - name: Cache Cypress binary
#             uses: actions/cache@v2
#         with:
#           path: ~/.cache/Cypress
#           key: ${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
#           restore-keys: |
#             ${{ runner.os }}-cypress-

#       name: Cypress run
#         uses: cypress-io/github-action@v6



# name: End-to-end tests
# on: push
# jobs:
#   cypress-run:
#     runs-on: ubuntu-24.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       # Install npm dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v6


name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache node_modules to speed up installation
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

